// RapierPhysicsWorld is type-only here so importers that only need the interface
// do not pull the WASM wrapper into their chunk. Value consumers (tests, the
// async physics bootstrap) import from './PhysicsWorld' directly.
export type {
  RapierPhysicsWorld,
  PhysicsWorld,
  Vec3,
  CharacterId,
  CharacterIntent,
  CharacterMoveResult,
  InteractionQuery,
  RayQuery,
  RayHit,
  CapsuleSweep,
  SweepHit,
  PathOptions,
  NavPath,
  SurfaceTag,
  StaticColliderSpec,
  StaticTrimeshSpec,
  CharacterBodySpec,
  GrenadeBodySpec,
  GrenadeBodySnapshot,
} from './PhysicsWorld';
export {
  NavigationGraph,
  CoverSlots,
  SquadDirector,
  planSquadRoles,
  type NavigationNode,
  type NavigationEdge,
  type NavigationPath,
  type CoverSlotDefinition,
  type CoverReservation,
  type CoverScoringOptions,
  type FlankNodeOptions,
  type SquadAgent,
  type SquadAssignment,
  type SquadAssignOptions,
  type SquadRole,
  type SquadRolePlan,
  type SquadRoleOptions,
} from './Navigation';
export {
  GameSession,
  type InputFrame,
  type GameEvent,
  type PlayerSnapshot,
  type InventorySnapshot,
  type WeaponSnapshot,
  type GameWorldSnapshot,
  type GameSnapshot,
  type GameSessionSystems,
  type GameSessionOptions,
} from './GameSession';
